### ISSUE TITLE
How to deploy with 

### ISSUE THREAD

**Issue by Iximiel** [plumed-tutorials/plumed-tutorials#12]
I am using this issue as a cheat-sheet for the new deploy procedure

Refer to [this link](https://github.com/peaceiris/actions-gh-pages?tab=readme-ov-file#%EF%B8%8F-create-ssh-deploy-key) for the images
I set up a script like this one to create a deploy key for each repo
```bash
#!/bin/bash

for page in nest tutorial testcenter; do
    ssh-keygen -t rsa -b 4096 -C "giovanni.bussi+plumedbot@gmail.com" -f "gh-pages-${page}" -N ""
done
```

Then to test it:
 - I added the text of the gh-pages-testcenter.pub to the *Deploy keys* in the repository settings of "plumed-testcenter/plumed-testcenter.github.io"
 - I added the  text of the private key text of the gh-pages-testcenter as a secret named `ACTIONS_DEPLOY_KEY` in the code repository "plumed-testcenter/plumed-testcenter"
 - I modified `.ci/push` to not push, but to "prepare the site" int `$HOME/tmp/deploy` 
 - I added the last step of the deployment job to:
```yaml
- name: Deploy to GitHub Pages
  uses: peaceiris/actions-gh-pages@v4
  if: github.ref == 'refs/heads/main'
  with:
      external_repository: plumed-testcenter/plumed-testcenter.github.io
      publish_branch: master
      deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      publish_dir: ./tmp/deploy
      force_orphan: true #this makes the last deploy to be the only commit
      enable_jekyll: true #by default jekyll is disabled
      user_name: 'PlumedBot'
      user_email: 'giovanni.bussi+plumedbot@gmail.com'
```
 - That impersonates the PlumedBot to upload everything that is in `./tmp/deploy` to the master branch of the plumed-testcenter/plumed-testcenter.github.io repo

From https://github.com/plumed-testcenter/plumed-testcenter.github.io/tree/master and https://plumed-testcenter.github.io/ you can see that it is working :smile:
